version: '3.4'
services:

  viewer:
    image: ohif/viewer:latest
    container_name: viewer
    depends_on:
      - orthanc
    restart: always
    ports:
      - '80:80'
    networks:
      - frontend
      - backend
    volumes:
      # Nginx as a reversed proxy for orthanc and the viewer
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # OHIF Viewer configuration to reach DICOMWeb endpoints
      - ./config/viewer.js:/usr/share/nginx/html/app-config.js:ro

  orthanc:
    image: jodogne/orthanc-plugins:latest
    container_name: orthanc
    depends_on:
      - postgres
    restart: always
    networks:
      - frontend
      - backend
    volumes:
      # configuration file
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
      # storage volume for raw dicoms
      - ./orthanc_db:/var/lib/orthanc/db
    environment:
      # DICOMWeb Plugin
      - DW_ENABLED=true
      # Postgres Plugin
      - PG_ENABLED=true
    command: /etc/orthanc/orthanc.json

  postgres:
    image: postgres:12.1
    container_name: postgres
    networks:
      - backend
    volumes:
      - ./pg_data/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=orthanc
      - POSTGRES_PASSWORD=pgpassword
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=orthanc

networks:
  frontend:
  backend: